name: Fail OK

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.10-dev, pypy3-dev]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox
      run: |
        python -m pip install tox
    - name: Run Tox
      env:
        TOX_SKIP_MISSING_INTERPRETERS: false
      run: |
        tox -e py

      continue-on-error: true

  pytest2:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, 3.10, 3]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: deadsnakes/action@v1.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox
      run: |
        python -m pip install tox
    - name: Run Tox
      env:
        TOX_SKIP_MISSING_INTERPRETERS: false
      run: |
        tox -e py

      continue-on-error: true
